AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS App for Summarising YouTube Podcasts
Parameters:
  MediaConvertRoleArn:
    Type: String
    Description: The ARN for the role previously to pass to MediaConvert so it can access to resources in your account
Resources:
  VideoSourceContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: video-source-container

  SoundOutputContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sound-output-container

  SoundStrip:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: sound-strip
      MemorySize: 128
      Timeout: 30
      Layers:
        - arn:aws:lambda:us-east-1:780954185713:layer:python-sound-manipulation:3
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess

  MediaConverter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: media-converter
      MemorySize: 128
      Timeout: 30

      Role: !GetAtt MediaConvertRole.Arn
      Environment:
        Variables:
          MEDIA_CONVERT_ROLE: !Ref MediaConvertRoleArn
      Events:
        S3Put:
          Type: S3
          Properties:
            Bucket: !Ref VideoSourceContainer
            Events: s3:ObjectCreated:*

  MediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - mediaconvert.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: MediaConvertPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: Logging
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Sid: PassRole
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !Ref MediaConvertRoleArn
              - Sid: MediaConvertService
                Effect: Allow
                Action:
                  - "mediaconvert:*"
                Resource:
                  - "*"
