AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS App for Summarising YouTube Podcasts
Parameters:
  AppsyncApiId:
    Type: String
  AmplifyFunctionName:
    Type: String
  AppsyncApiUrl:
    Type: String
Resources:
  VideoSourceContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: video-source-container
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Metadata:
      SamResourceId: VideoSourceContainer
  SoundOutputContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sound-transcribed-output
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Metadata:
      SamResourceId: SoundOutputContainer
  TranscribedTextsContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: transcribed-texts-container
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Metadata:
      SamResourceId: TranscribedTextsContainer
  SoundStrip:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: s3://nick-gen-purpose/63e591b4fe03d940f9eb47d2eacd51f8
      MemorySize: 128
      Timeout: 30
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:python-sound-manipulation:7
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonS3FullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /soundstrip
            Method: post
            RestApiId:
              Ref: SoundStripApi
    Metadata:
      SamResourceId: SoundStrip
  SoundStripApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SoundStripApi
      StageName: Prod
      Auth:
        DefaultAuthorizer: IAM
        Authorizers:
          IAM:
            Identity:
              Headers:
              - Authorization
            FunctionArn:
              Fn::GetAtt:
              - SoundStrip
              - Arn
            FunctionPayloadType: REQUEST
            IdentitySource: method.request.header.Authorization
    Metadata:
      SamResourceId: SoundStripApi
  SoundTranscriber:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: s3://nick-gen-purpose/f77e391b0e25c30d287c0d8a75630810
      MemorySize: 128
      Timeout: 30
      Role:
        Fn::GetAtt:
        - SoundTranscriberRole
        - Arn
      Events:
        S3PutObject:
          Type: S3
          Properties:
            Bucket:
              Ref: VideoSourceContainer
            Events:
            - s3:ObjectCreated:Put
            - s3:ObjectCreated:CompleteMultipartUpload
    Metadata:
      SamResourceId: SoundTranscriber
  TranscribeSummariser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: s3://nick-gen-purpose/87b2d9ed0eb8f4d52aa5ad29fab36f3f
      MemorySize: 128
      Timeout: 30
      Role:
        Fn::GetAtt:
        - TranscribeSummariserRole
        - Arn
      Environment:
        Variables:
          APPSYNC_API_URL:
            Ref: AppsyncApiUrl
      Events:
        S3PutObject:
          Type: S3
          Properties:
            Bucket:
              Ref: SoundOutputContainer
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .json
    Metadata:
      SamResourceId: TranscribeSummariser
  SoundStripInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - SoundStrip
        - Arn
      Principal: amplify.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AmplifyFunctionName}
    Metadata:
      SamResourceId: SoundStripInvokePermission
  SoundTranscriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - transcribe.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
      - PolicyName: TranscribeServicePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - transcribe:StartTranscriptionJob
            - transcribe:GetTranscriptionJob
            - transcribe:ListTranscriptionJobs
            - transcribe:DeleteTranscriptionJob
            Resource: '*'
    Metadata:
      SamResourceId: SoundTranscriberRole
  TranscribeSummariserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
      - PolicyName: DynamoDBCrudPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            Resource:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/News-vcydekvyjzhqpbz6wzbzrxyndu-NONE
      - PolicyName: BedrockInvokeModelPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: BedrockService
            Effect: Allow
            Action:
            - bedrock:InvokeModel
            Resource: '*'
      - PolicyName: AccessAmplifyApi
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: appsync:GraphQL
            Resource:
              Fn::Sub: arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${AppsyncApiId}/*
    Metadata:
      SamResourceId: TranscribeSummariserRole
Outputs:
  SoundStripApiUrl:
    Description: URL for the SoundStrip API
    Value:
      Fn::Sub: https://${SoundStripApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/soundstrip
