AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS App for Summarising YouTube Podcasts
# Parameters:
#   MediaConvertRoleArn:
#     Type: String
#     Description: The ARN for the role previously to pass to MediaConvert so it can access to resources in your account
Parameters:
  AppsyncApiId:
    Type: String
  AmplifyFunctionName:
    Type: String
  AppsyncApiUrl:
    Type: String
Resources:
  VideoSourceContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: video-source-container
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SoundOutputContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sound-transcribed-output
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TranscribedTextsContainer:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: transcribed-texts-container
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SoundStrip:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: sound-strip
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:python-sound-manipulation:7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
  #     Events:
  #       ApiEvent:
  #         Type: Api
  #         Properties:
  #           Path: /soundstrip
  #           Method: post
  #           RestApiId: !Ref SoundStripApi

  # SoundStripApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     Name: SoundStripApi
  #     StageName: Prod
  #     Auth:
  #       DefaultAuthorizer: IAM
  #       Authorizers:
  #         IAM:
  #           Identity:
  #             Headers:
  #               - Authorization
  #           FunctionArn: !GetAtt SoundStrip.Arn
  #           FunctionPayloadType: REQUEST
  #           IdentitySource: method.request.header.Authorization

  SoundTranscriber:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: sound-transcriber
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt SoundTranscriberRole.Arn
      Events:
        S3PutObject:
          Type: S3
          Properties:
            Bucket: !Ref VideoSourceContainer
            Events:
              - s3:ObjectCreated:Put
              - s3:ObjectCreated:CompleteMultipartUpload
  TranscribeSummariser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: transcribe-summariser
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt TranscribeSummariserRole.Arn
      Environment:
        Variables:
          APPSYNC_API_URL: !Ref AppsyncApiUrl
      Events:
        S3PutObject:
          Type: S3
          Properties:
            Bucket: !Ref SoundOutputContainer
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .json

  SoundStripInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SoundStrip.Arn
      Principal: amplify.amazonaws.com
      SourceArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AmplifyFunctionName}

  SoundTranscriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - transcribe.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: TranscribeServicePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - transcribe:ListTranscriptionJobs
                  - transcribe:DeleteTranscriptionJob
                Resource: "*"

  TranscribeSummariserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: BedrockInvokeModelPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: BedrockService
                Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: "*"
        - PolicyName: AccessAmplifyApi
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: appsync:GraphQL
                Resource: !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${AppsyncApiId}/*"
# Outputs:
#   SoundStripApiUrl:
#     Description: "URL for the SoundStrip API"
#     Value: !Sub "https://${SoundStripApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/soundstrip"
# "{statusCode=500, error={"message":{"name":"AccessDeniedException","$fault":"client","$metadata":{"httpStatusCode":403,"requestId":"991c5a54-5948-434c-b420-2fb9fd3e977e","attempts":1,"totalRetryDelay":0},"message":"User: arn:aws:sts::780954185713:assumed-role/amplify-d2jx79cpuvq9e1-ma-sayhellolambdaServiceRole-SHp3ZTK7wjPW/amplify-d2jx79cpuvq9e1-main-sayhellolambdaEFA46D92-3DN0Q34QF1K7 is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:780954185713:function:aws because no identity-based policy allows the lambda:InvokeFunction action"}}}"

# "{statusCode=500, error={\"message\":{\"name\":\"AccessDeniedException\",\"$fault\":\"client\",\"$metadata\":{\"httpStatusCode\":403,\"requestId\":\"40e9239b-1215-4811-ad97-d56796b13096\",\"attempts\":1,\"totalRetryDelay\":0},\"message\":\"User: arn:aws:sts::780954185713:assumed-role/amplify-d2jx79cpuvq9e1-ma-sayhellolambdaServiceRole-SHp3ZTK7wjPW/amplify-d2jx79cpuvq9e1-main-sayhellolambdaEFA46D92-3DN0Q34QF1K7 is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:780954185713:function:aws because no identity-based policy allows the lambda:InvokeFunction action\"}}}"
